rest:
  template:
    timeout: 40000


logging:
  level:
    za.co.fnb.pop.branch: debug
  
my:
  greeting: "Hello, I am from config server"
  

management:
  endpoints:
    web:
      exposure:
        include: refresh
        
logging:
  level:
    za.co.fnb.pop.branch: debug
